# Generated by Django 3.2.6 on 2021-09-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210904_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductsCategory',
        ),
    ]
